version: "3.8"
services:
  postgres:
    build: ./postgres
    image: postgres:14.2
    # restart: always
    environment:
      - POSTGRES_USER=pipegine-app
      - POSTGRES_PASSWORD=pipegine-app
      - POSTGRES_DB=pipegine
    ports:
      - '5432:5432'
    volumes:
      - .volume/postgres:/var/lib/postgresql/data